name: Auto Merge to Master

on:
  pull_request:
    types: [closed]

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge changes to master
        run: |
          git checkout master
          git merge ${{ github.event.pull_request.head.ref }} --no-ff --commit -m "Merge pull request #${{ github.event.pull_request.number }} from ${{ github.event.pull_request.head.ref }}"

      - name: Push changes to master
        run: git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
